-- | That module is needed in order to use repl. When building it would be
--   replaced with the one generated by cabal
module Paths_commonmark_testutils where

getDataFileName :: FilePath -> IO FilePath
getDataFileName = pure
